### ISSUE TITLE
The directory name is invalid.

### ISSUE THREAD

**Issue by Pijuten** [iochen/skillshare-dl#1]
The title includes a colon and it can't creat a directory and crashes with the error:
_level=error msg="mkdir {Name of course}: The directory name is invalid."
Is there a worke around?_

**Comment by rikkihamano** [comment]
I have stopped using skillshare, so I cannot test it.
If the issue still exists, please reopen it, and I'll try other solutions.

**Comment by Pijuten** [comment]
Workes like a charm!
A huge thank you :)
