### ISSUE TITLE
Virus Detected by AVG

### ISSUE THREAD

**Issue by dotrock** [iochen/skillshare-dl#5]
On windows it's detected virus by AVG, please fix this issue.

Thanks

**Comment by rikkihamano** [comment]
Source Code: https://github.com/iochen/skillshare-dl
Build & Release Process: https://github.com/iochen/skillshare-dl/runs/2869365622
If you like, you can see everything I had done to this tool.

Sorry, I cannot fix it, either ignore the warning or stop using this tool.
